### PR TITLE
Added script to import edge outputs from 2023 spreadsheet

### PR DESCRIPTION
**Pull request by raldi**

### CODE REVIEW

**Comment by jkbelcher** [comment]
Changed to a soft warning in #218 .  Also includes an image of the 8 conflicts.

**Comment by jkbelcher** [comment]
image

**Comment by raldi** [comment]
The errors are legit; the spreadsheet had bad data. Fixing and re-exporting...

**Comment by raldi** [comment]
Tested this; seems to work

**Comment by jkbelcher** [comment]
Works for me.  I'm going to bring in #218 too, the friendly error handling seems reasonable.

**Review by jkbelcher — APPROVED** [review]
Tested, runs without error.

**Pull request merged**
