### PR TITLE
WIP: Fixtures round 2

### PR DESCRIPTION
**Pull request by fakeplant**
Fixture param changes based on latest module fixing.

Includes changes to TE_car.lxm + backfills to fixture files.

Fixture file backfills are handled with node script:
https://github.com/fakeplant/lxs

Also includes a test model called TE_warehouse.lxm used for running arbitrary module arrangements at warehouse.

### CODE REVIEW

**Comment by fakeplant** [comment]
@jkbelcher this is generally good to go. 
However, LX crashed on me a couple times when dealing w/ model files.
I couldn't repro it, but it happened when TE server was power cycled (accidently happened from electricians working at warehouse) and it'd reboot into whatever the default auto startup project was. When i switched projects into CoachellaMaster thru the UI it wouldnt show the model file and would sometimes freak out. When i manually reset the program thru Intellij it all seemed fine. Guessing the auto startup sequence is messed up (maybe missing -dynamic prop or something)

**Comment by jkbelcher** [comment]
I don't know what version of our software auto-starts on boot, likely an older jar that should not be used.  You could ask @worldveil who set up the app before the last event.  Definitely just close it and run from intellij.

**Comment by jkbelcher** [comment]
Backfilling from lxm to lxf looks great.  Thanks for making at app for it.

Can we revert changes to CoachellaMaster.lxp and Oct21.lxp?  We're trying to leave those as-is for historical reference, also avoiding noise from unnecessary project file changes.

**Comment by fakeplant** [comment]
@jkbelcher yeah we can revert those project changes.

**Comment by andrewlook** [comment]
@fakeplant @jkbelcher is this one ready to merge? happy to get it merged in even if we still have changes to make, just wanted to double-check

**Review by jkbelcher — APPROVED** [review]
Tested.  Both models load fine.

**Comment by jkbelcher** [comment]
Looks ready to me.  Thanks @fakeplant !  Merging.

**Pull request merged**
