### PR TITLE
Skynet MVP

### PR DESCRIPTION
**Pull request by raldi**
I haven't yet tested if this is properly outputting to controllers.

### CODE REVIEW

**Comment by twrankin** [comment]
> I haven't yet tested if this is properly outputting to controllers.

Thanks so much for this! I'll take a look at the changes tonight/tomorrow night and hook it up to my small test setup.

**Comment by raldi** [comment]
@twrankin Do we still need this or can I close it?

**Comment by worldveil** [comment]
If this is no longer needed or relevant, would love to close.

**Comment by raldi** [comment]
I wrote this to be mergeable; it wouldn't interfere with the TE vehicle code, because all the new stuff would only be triggered if you passed "skygrid" on the command line. But I don't want to put the complexity in the codebase if we're never going to use it again.

@twrankin, what are the ongoing plans for your piece?

**Comment by twrankin** [comment]
It’s not happening this year, and if it did I would cook up something cleaner. Feel free to close.

-Trent

On Jun 5, 2023, at 8:55 AM, raldi ***@***.***> wrote:



I wrote this to be mergeable; it wouldn't interfere with the TE vehicle code, because all the new stuff would only be triggered if you passed "skygrid" on the command line. But I don't want to put the complexity in the codebase if we're never going to use it again.

@twrankin<https://github.com/twrankin>, what are the ongoing plans for your piece?

**Pull request closed without merging**
