### PR TITLE
Upgrade to Chromatik

### PR DESCRIPTION
**Pull request by jkbelcher**
This is usable from my perspective.  We should consider a merge timeline that allows time to discover and sort any issues.  I added a branch "preChromatik" capturing the current state in case we want to merge but still access the current version.

Special thanks to @zranger1 for getting shaders working!

Edit: Also thanks to @andrewlook for the jvm config.

### CODE REVIEW

**Review by zranger1 — APPROVED** [review]
Justin, I'm good with this - it's working fine on Mac/Windows - so going to approve.   Because this is a huge change, before you merge though, I'd greatly prefer if we had a couple of other people's review and test results.

My wishlist of tiny bugs, to be addressed when you get time:
- fix vehicle orientation and position in the viewport on startup.  It winds up somewhere a little strange ATM.
- can we change the run config files to do different things on different platforms?   Windows doesn't like the -XstartOnFirstThread flag.  I don't mind fixing my own build configs when using the PC, but it'd be nice to stay cross platform compatibile.
- next time we pull a Chromatik build, can you try to get the linux-amd64 libraries too?   I'd like to run some automated long term tests on Linux, but alas, not w/the current Chromatik snapshot.   (linux-arm64 is there though.  Yay, raspberry pi!)

**Comment by jkbelcher** [comment]
@zranger1 Fixed the startup camera orientation.

**Comment by jkbelcher** [comment]
> can we change the run config files to do different things on different platforms? Windows doesn't like the -XstartOnFirstThread flag. I don't mind fixing my own build configs when using the PC, but it'd be nice to stay cross platform compatibile.

Sounds good, do you know offhand how to do that?  Which run configs? There are different ones for headless, maven shortcut, eclipse, and intellij.

> next time we pull a Chromatik build, can you try to get the linux-amd64 libraries too? I'd like to run some automated long term tests on Linux, but alas, not w/the current Chromatik snapshot. (linux-arm64 is there though. Yay, raspberry pi!)

I'll check on whether that's available.

**Comment by zranger1** [comment]
No clue how to get multiplatform run config working for everything.  I'll look into it, but meantime, if it works on Mac, it's good enough for me.

**Comment by worldveil** [comment]
A couple things:

1. I'm not able to get this to work in IntelliJ - does anyone have a run configuration they could share? Otherwise I can only run with `mvn clean package && java -XstartOnFirstThread -Djava.awt.headless=true -jar target/LXStudio-TE-0.2.1-SNAPSHOT-jar-with-dependencies.jar vehicle`
1. I see a TON of these (thousands) on shutdown:

```
... <many more> 
[LX 2023/07/22 11:12:35] <WARNING> Stranded UI listener on parameter: /lx/mixer/channel/14/pattern/42/te_color - titanicsend.ui.UITEColorPicker$$Lambda$279/0x000000080032a3f8
[LX 2023/07/22 11:12:35] <WARNING> Stranded UI listener on parameter: /lx/mixer/channel/14/pattern/42/te_color/gradient - heronarts.glx.ui.component.UIKnob
[LX 2023/07/22 11:12:35] <WARNING> Stranded UI listener on parameter: /lx/mixer/channel/14/pattern/42/te_speed - heronarts.glx.ui.component.UIKnob
[LX 2023/07/22 11:12:35] <WARNING> Stranded UI listener on parameter: /lx/mixer/channel/14/pattern/42/te_xpos - heronarts.glx.ui.component.UIKnob
... <many more> 
```

**Comment by jkbelcher** [comment]
> I see a TON of these (thousands) on shutdown:

Yep, it's on the list but not hurting anything.

**Comment by worldveil** [comment]
Added configuration file specifically for running in IntelliJ.

I think people will still have to specify the Java JDK manually, since this appears in the file:

```
<option name="ALTERNATIVE_JRE_PATH" value="temurin-17 - SonicSphere (aarch64)" />
```

which I is just my string from naming it myself in my IDE. Any ideas how to make this universal to different machines / install locations?

**Comment by jkbelcher** [comment]
@worldveil The run config looks redundant with the `Titanic's End.run.xml` file added by @andrewlook in the same directory.  I don't think we need two of them... can you adjust your system to use the one that was already there?

**Comment by jkbelcher** [comment]
> > I see a TON of these (thousands) on shutdown:
> 
> Yep, it's on the list but not hurting anything.

Fixed the UI-related ones.  There are a couple more still to fix.

**Comment by jkbelcher** [comment]
> > I see a TON of these (thousands) on shutdown:
> 
> Yep, it's on the list but not hurting anything.
> 

These should all be fixed now. @worldveil

**Pull request merged**
