### PR TITLE
GPOutput looks on all channels for TEPattern instead of just the first

### PR DESCRIPTION
**Pull request by jkbelcher**
Not tested, please test.

### CODE REVIEW

**Review by raldi — APPROVED** [review]
Can't test this at the moment but the code looks good

**Comment by raldi** [comment]
@ssilverman are you available to test this?

**Comment by ssilverman** [comment]
Yes, this evening.

**Comment by jkbelcher** [comment]
Pushed simple fix - forgot to increment the integer and got stuck in infinite While loop.  Still would be good if someone tests the actual output.

**Comment by jkbelcher** [comment]
Proposed #167 as a better alternative.  Leaving this open for now because it would work if you choose.

**Pull request closed without merging**
