### PR TITLE
Look: pattern prototype using CPPN

### PR DESCRIPTION
**Pull request by andrewlook**
making a simple version of this architecture: https://blog.otoro.net/2016/03/25/generating-abstract-patterns-with-tensorflow/

using beatscaled time input so animation varies over time (responsive to the tempo, scaled by beatScale parameter).

### CODE REVIEW

**Comment by andrewlook** [comment]
https://user-images.githubusercontent.com/236018/183547934-50c8cf33-f2ff-4e3e-b7ac-012a30dc65c1.mp4

**Comment by jvyduna** [comment]
Hey! Welcome, Andrew! This is exciting. Before we merge, can you add a few enhancements to fit in with our show?

1. Please give your shader a new name, as it doesn't present very much like FollowThatStar
2. I don't know much about CPPN, but could you cajole it to generate a rainbow that's somehow based around our palette entries? We want that main LinkedColorParameter to be functional
3. The car is so large that in person, we find we really want everything much slow than you think. Can you rescale the speed such that it's lowest speed is almost frozen, and the fastest is about 25% of current max?
4. We also wish to have an energy parameter that works for all patterns. Maybe for something like this, you pulse the timebase to the tempo, and the amount of time skewing is related to how high the energy parameter is. For examples of this, see the TempoReactiveEdge pattern. Feel free to reuse that code here.

Check out the recently updated [Art Direction Standards](https://docs.google.com/document/d/16FGnQ8jopCGwQ0qZizqILt3KYiLo0LPYkDYtnYzY7gI/edit) and [Using tempo and sound](https://docs.google.com/document/d/17iICAfbhCzPL77KbmFDL4-lN0zgBb1k6wdWnoBSPDjk/edit#heading=h.c128mhwk0z9z). We're going to hopefully get everyone's patterns up to these standards!

**Comment by jvyduna** [comment]
Would love to invite you to our Slack workspace as well. Send me a good email to add you! jeff@jeffvyduna.com

**Comment by andrewlook** [comment]
> Hey! Welcome, Andrew! This is exciting. Before we merge, can you add a few enhancements to fit in with our show?
> 

Thanks for the feedback, @jvyduna ! Apologies for the slow reply here. 

> 1. Please give your shader a new name, as it doesn't present very much like FollowThatStar

Sorry about that - done!

> 2. I don't know much about CPPN, but could you cajole it to generate a rainbow that's somehow based around our palette entries? We want that main LinkedColorParameter to be functional

Sounds good, easy enough for me to modulate HSV of the selected palette color.

It seems that the global panel has many palettes, each w/ several colors - but only 1 color should be used by any given animation (as described by `LinkedColorParameter`), is that correct?

> 3. The car is so large that in person, we find we really want everything much slow than you think. Can you rescale the speed such that it's lowest speed is almost frozen, and the fastest is about 25% of current max?

Sounds good, that makes total sense 👍 

> 4. We also wish to have an energy parameter that works for all patterns. Maybe for something like this, you pulse the timebase to the tempo, and the amount of time skewing is related to how high the energy parameter is. For examples of this, see the TempoReactiveEdge pattern. Feel free to reuse that code here.

Sounds good - thanks for the explainer of energy, I didn't understand it quite so clearly when I first read through the Art Standards / Using Tempo docs.

Just to make sure I understand this correctly, would it resemble the snippet of code below? I think that what you're describing would mean swapping out beatScale for something like energy (with the arithmetic rejigged so higher energy means time skew is higher when bpm is higher)?

```java
        timebase = ((double) System.currentTimeMillis()) / 1000.0;

        // t1 applies a speed factor to the BPM, multiplies it into the time
        double beat = lx.engine.tempo.bpm() / beatScale.getValue();

        t1 = timebase * beat;
```

As an aside: In the code I not-so-carefully forked from FollowThatStar, there were 2 "controls". I think "energy" is covered by the art standards and is required, while beatScale was peculiar to FollowThatStar. Does that mean it's okay to remove beatScale from my new pattern?

```java
    // Controls
    public final CompoundParameter energy =
            new CompoundParameter("Energy", .5, 0, 1)
                    .setDescription("Stars sparkle and move");

    protected final CompoundParameter beatScale = (CompoundParameter)
            new CompoundParameter("Speed", 60, 120, 1)
                    .setExponent(1)
                    .setUnits(LXParameter.Units.INTEGER)
                    .setDescription("Overall movement speed");
``` 

> 
> Check out the recently updated [Art Direction Standards](https://docs.google.com/document/d/16FGnQ8jopCGwQ0qZizqILt3KYiLo0LPYkDYtnYzY7gI/edit) and [Using tempo and sound](https://docs.google.com/document/d/17iICAfbhCzPL77KbmFDL4-lN0zgBb1k6wdWnoBSPDjk/edit#heading=h.c128mhwk0z9z). We're going to hopefully get everyone's patterns up to these standards!

Nice, thanks!

summary of my next steps:
- [x] rename pattern
- [ ] modulate HSV of the selected palette color.
- [ ] rescale the speed such that it's lowest speed is almost frozen, and the fastest is about 25% of current max
- [ ] pulse the timebase to the tempo, and the amount of time skewing is related to how high the energy parameter (ref: TempoReactiveEdge)

**Comment by andrewlook** [comment]
Split out CPPN Pattern variants into more descriptively-named patterns, since the underlying framework can support a decent variety of abstract patterns.

## Neural Waves

Implemented speed changes and palette support - haven't integrated energy param into this one yet, but I experimented with ways to use energy in some other patterns (see below) and could adapt those ideas to this pattern if you think they make sense.

https://user-images.githubusercontent.com/236018/185670007-84e3844d-fa30-4da1-851a-9791ea75b109.mp4

TODO before merging:
- [ ] remove my custom project files/etc

## Other ideas

### Neural Beat Radial

Energy param causes swingbeat to make a radial "speaker beat" effect. Probably need to tune down the speed on this one.

https://user-images.githubusercontent.com/236018/185669747-79210483-cee3-482d-a87c-b08a4d62577e.mp4

FYI there are some other variants depending on how we use tan/tanh functions in this one - I kind of like how this one actually looks like a big speaker :)

https://user-images.githubusercontent.com/236018/185670280-3d5452ad-3645-4d7a-9a34-0c1154d629cb.mp4

**Comment by jvyduna** [comment]
Ran all 4 patterns all night, no crash or memory leak.

**Review by jvyduna — APPROVED** [review]

**Pull request merged**
