### PR TITLE
OSC handler for audio stems

### PR DESCRIPTION
**Pull request by jkbelcher**
Adds a top-level component to monitor OSC messages for audio stem float values.  Stores the values in parameters where they can be used for mappings or by calling the static accessor e.g.:

`AudioStems.current.drums.getValue()`

image

### CODE REVIEW

**Comment by jkbelcher** [comment]
Demo:
[](https://www.youtube.com/watch?v=wslrXm5dyXY)

**Comment by worldveil** [comment]
Looks good to me. We can eventually do moving averages and historical normalization here too if we want!

Will shaders be able to access these values eventually?

**Comment by jkbelcher** [comment]
> Looks good to me. We can eventually do moving averages and historical normalization here too if we want!

Exactly.  That's why I left a handler method for each stem.

> Will shaders be able to access these values eventually?

Java patterns can access them now through the static `AudioStems.current`.  For the final version we might want to route this stuff through an abstraction layer to keep flexibility for the end user.

**Review by worldveil — DISMISSED** [review]

**Comment by jkbelcher** [comment]
Replaced by #500

**Pull request closed without merging**
