### PR TITLE
Add startup-time shader cache manager

### PR DESCRIPTION
**Pull request by zranger1**
The shader cache is now checked at each LX startup, and precompiled binaries for any new or updated shaders are generated and saved in the ```resources/shaders/cache``` directory.

This is completely automatic and, until we're dealing with hundreds of shaders, should have no noticeable effect on startup times. (there's a timer in the log, if you want to check!)

Having all the shaders precompiled means that shader pattern load times will be consistently fast, even the very first time you load a pattern.

Manual override instructions:
- To clear the cache, delete all the ```.bin``` files from ```resources/shaders/cache```
- To disable caching entirely, delete or empty, then write protect the cache directory.

### CODE REVIEW

**Comment by worldveil** [comment]
When I run, I am seeing this error:

```
[LX 2022/07/27 19:28:36] LXStudio onUIReady call-back threw an exception: null
java.lang.RuntimeException: java.lang.RuntimeException: Error producing shader!
Validation Failed: Program does not contain vertex shader. Results will be undefined.

	at titanicsend.pattern.jon.ShaderPrecompiler.rebuildCache(ShaderPrecompiler.java:87)
	at titanicsend.app.TEApp.onUIReady(TEApp.java:301)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at heronarts.lx.studio.LXStudio.callback(LXStudio.java:174)
	at heronarts.lx.studio.LXStudio.onUIReady(LXStudio.java:197)
	at heronarts.lx.studio.LXStudio.<init>(LXStudio.java:135)
	at titanicsend.app.TEApp.setup(TEApp.java:94)
	at processing.core.PApplet.handleDraw(PApplet.java:2142)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:822)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.RuntimeException: Error producing shader!
Validation Failed: Program does not contain vertex shader. Results will be undefined.

	at titanicsend.pattern.yoffa.shader_engine.ShaderUtils.validateStatus(ShaderUtils.java:253)
	at titanicsend.pattern.yoffa.shader_engine.ShaderUtils.link(ShaderUtils.java:216)
	at titanicsend.pattern.jon.ShaderPrecompiler.rebuildCache(ShaderPrecompiler.java:81)
	... 22 more
```

**Comment by zranger1** [comment]
Vertex shader error should be fixed now.

**Comment by worldveil** [comment]
Hmm, still seeing it

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at heronarts.lx.studio.LXStudio.callback(LXStudio.java:174)
	at heronarts.lx.studio.LXStudio.onUIReady(LXStudio.java:197)
	at heronarts.lx.studio.LXStudio.<init>(LXStudio.java:135)
	at titanicsend.app.TEApp.setup(TEApp.java:94)
	at processing.core.PApplet.handleDraw(PApplet.java:2142)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:822)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error producing shader!
Validation Failed: Program does not contain vertex shader. Results will be undefined.

	at titanicsend.pattern.jon.ShaderPrecompiler.rebuildCache(ShaderPrecompiler.java:87)
	at titanicsend.app.TEApp.onUIReady(TEApp.java:301)
	... 21 more
Caused by: java.lang.RuntimeException: Error producing shader!
Validation Failed: Program does not contain vertex shader. Results will be undefined.

	at titanicsend.pattern.yoffa.shader_engine.ShaderUtils.validateStatus(ShaderUtils.java:253)
	at titanicsend.pattern.yoffa.shader_engine.ShaderUtils.link(ShaderUtils.java:216)
	at titanicsend.pattern.jon.ShaderPrecompiler.rebuildCache(ShaderPrecompiler.java:81)
	... 22 more
```

**Comment by zranger1** [comment]
Changed to super conservative compile strategy.   Let me know if this fixes it.  If not, I'll go dig up a different machine to debug on.

**Comment by worldveil** [comment]
This is what I see now:

```
[LX 2022/07/28 18:06:20] LXStudio onUIReady call-back threw an exception: null
java.lang.RuntimeException: java.lang.RuntimeException: Error producing shader!
ERROR: 0:84: No matching function for call to texture(sampler2D, vec3)
ERROR: 0:105: No matching function for call to texture(sampler2D, vec3)
ERROR: 0:133: No matching function for call to texture(sampler2D, vec3)

	at titanicsend.pattern.jon.ShaderPrecompiler.rebuildCache(ShaderPrecompiler.java:96)
	at titanicsend.app.TEApp.onUIReady(TEApp.java:301)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at heronarts.lx.studio.LXStudio.callback(LXStudio.java:174)
	at heronarts.lx.studio.LXStudio.onUIReady(LXStudio.java:197)
	at heronarts.lx.studio.LXStudio.<init>(LXStudio.java:135)
	at titanicsend.app.TEApp.setup(TEApp.java:94)
	at processing.core.PApplet.handleDraw(PApplet.java:2142)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:822)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.RuntimeException: Error producing shader!
ERROR: 0:84: No matching function for call to texture(sampler2D, vec3)
ERROR: 0:105: No matching function for call to texture(sampler2D, vec3)
ERROR: 0:133: No matching function for call to texture(sampler2D, vec3)

	at titanicsend.pattern.yoffa.shader_engine.ShaderUtils.validateStatus(ShaderUtils.java:253)
	at titanicsend.pattern.yoffa.shader_engine.ShaderUtils.createShader(ShaderUtils.java:123)
	at titanicsend.pattern.jon.ShaderPrecompiler.rebuildCache(ShaderPrecompiler.java:84)
	... 22 more
```

**Comment by worldveil** [comment]
Issue was related to shadder files that were invalid & not checked in!

**Pull request merged**
