### PR TITLE
DMX Grid Modulator

### PR DESCRIPTION
**Pull request by jkbelcher**
Stretch goal achieved: Receives a 2D grid over DMX and makes it available to DmxGridPattern which maps it to the TE fixtures.  Can be run on a dedicated channel for receiving a swipe effect from an external lighting board.

Demo:

https://www.youtube.com/watch?v=sPlDItBaxd0

### CODE REVIEW

**Review by zranger1 — APPROVED** [review]
Nice - we'll soon need to write our own iPad app to use all these new features!

**Comment by andrewlook** [comment]
Thanks for testing @zranger1 - I'll merge this for now and check out the setup in GrandMA.lxp.

Once I finish the other showfile prep work on my plate, I'll try to get the extra DMX Grid Modulator and the extra channel w/ DMX Grid Pattern integrated into Oct 21 showfile, and reach out to @jkbelcher if I get stuck.

P.S. @jkbelcher do you happen to have a project file for the "client" LX project you used to test this out?

**Comment by jkbelcher** [comment]
> P.S. @jkbelcher do you happen to have a project file for the "client" LX project you used to test this out?

No, it takes a different repo that doesn't use a static model like TE does.

**Comment by andrewlook** [comment]
ah okay thanks, i'll try experimenting with that on my own some other time

**Pull request merged**
