### PR TITLE
Add brightness back to a visible UI knob

### PR DESCRIPTION
**Pull request by jkbelcher**
Let there be... not so much light?

### CODE REVIEW

**Comment by worldveil** [comment]
Hm, I'm not seeing the knob in Design mode.

**Review by zranger1 — APPROVED** [review]
Approved -  Working as expected here + not much code change.

Might be nice to see it somewhere in performance mode too, even if it's not on a knob, just so you can be sure the value is what you think it is.

**Comment by worldveil** [comment]
@zranger1 wait are you seeing it working? I am not. I should be seeing a brightness, knob, yes?



Here I do not.

**Comment by worldveil** [comment]
@zranger1 wait are you seeing it working? I am not. I should be seeing a brightness, knob, yes?

Screenshot 2023-05-15 at 5 39 35 PM

Here I do not.

**Comment by zranger1** [comment]
I've got a functional brightness control.  It's a bit far off to the side, did it just get pushed out of the window?

image

**Comment by worldveil** [comment]
Nice, yep, I see it, Just needed to scroll over I think (lol).

**Pull request merged**
