### PR TITLE
Starting a list of patterns that don't respect color palette

### PR DESCRIPTION
**Pull request by andrewlook**
I just wanted to start a [list of patterns that do not respect palette](https://www.notion.so/titanicsend/Catalog-list-of-patterns-that-do-not-respect-palette-59c5a538668f4b4fbffe3b02e43556a6?pvs=4), so adding comments was the easiest way to start a draft PR while I work.

Next steps:
- I'll take a second pass through all the patterns and see if I missed any patterns
- For each of the patterns in question, I'll see if there's a clean way to swap in our palette (might ask for feedback as I go)

### CODE REVIEW

**Comment by theyoffa** [comment]
Similar to the other one, if we can dynamically create that list, should be super easy to extend for detecting `iColorRGB`. We could plug it into updating the `palette` param, since that also won't work in this case and we could similarly autogen. This would future proof and keep in sync.

**Comment by zranger1** [comment]
I've fixed two of the weirder ones, fire.fs and neontriangles.fs, in PR #341.

(We did a last-second EDC change to neon triangles to use iColorRGB for its main triangle color. But it also had a complicated 3D dithering pass for generating bloom, with its own color generator, that we just didn't get around to fixing on the moment.  The moral is, I guess, watch out for glow and other secondary color effects when testing these!)

**Comment by worldveil** [comment]
+1 to autogen of some sort that is future proof as @theyoffa mentioned

**Comment by andrewlook** [comment]
> Similar to the other one, if we can dynamically create that list, should be super easy to extend for detecting `iColorRGB`. We could plug it into updating the `palette` param, since that also won't work in this case and we could similarly autogen. This would future proof and keep in sync.

Autogenerating the list generation makes sense to me.

What do you mean by "plug it into updating the `palette` param, since that also won't work in this case"?

**Comment by theyoffa** [comment]
so there's a palette common parameter that switches which colors are used. not sure if you were thinking about that or the main palette, but if one doesn't work, that other won't either. since that's not working in this case, we can update the palette param with an [x] just like your other PR.

**Comment by andrewlook** [comment]
Quick update: I'll avoid touching the control labels till I have a better sense for how we want to signal touchOSC

I did make a list of the (shader-only) patterns that don't use at least one of `iColorRGB,iColorHSB,iColor2RGB,iColor2HSB` followed by the Shader classes that reference them (note there's a few fragment shaders with no Java patterns referencing them)

```
testshader.fs	[]
circuitry.fs	[]
neon_heart.fs	['NeonHeartNative']
audio_test.fs	[]
pulsing_heart.fs	['PulsingHeart']
combustable_veronoi.fs	[]
warp.fs	['Warp']
spectrum_analyzer1.fs	[]
synth_waves.fs	['SynthWaves']
jet_stream.fs	['JetStream']
neon_cells.fs	['NeonCells']
```

**Comment by andrewlook** [comment]
closing in favor of #332

**Pull request closed without merging**
