### PR TITLE
Turn on artnet sequence number

### PR DESCRIPTION
**Pull request by jkbelcher**
Recommended for use by Eli.

### CODE REVIEW

**Comment by worldveil** [comment]
What is the actual benefit here? Reluctant to merge until we can test on hardware again.

**Comment by raldi** [comment]
How does this interact with the situation where multiple are broadcasting at the same time?

**Comment by raldi** [comment]
BTW, this is the sort of thing that could go here if you wanted to make it configurable:
https://github.com/titanicsend/LXStudio-TE/blob/main/resources/vehicle/general.txt

**Comment by jkbelcher** [comment]
> How does this interact with the situation where multiple are broadcasting at the same time?

Well it would be hard to make that situation worse.  Behavior would depend on alignment of sequence numbers from the two sources and the controller code.  Sequence numbers in artnet go from 1 to 255 then start over.

**Review by raldi — APPROVED** [review]

**Comment by jkbelcher** [comment]
Merging to clean up PRs.  Added a P2 software task to make this configurable in general.txt per raldi's suggestion.

**Pull request merged**
